### ISSUE TITLE
Do you have the lastest imeidb data?

### ISSUE THREAD

**Issue by sovi123** [Veritas83/IMEIDB#1]
Looking forward to your reply.

**Comment by fiamma06** [comment]
Yes of course.

**Comment by sovi123** [comment]
> Yes of course.

How could I get the data?

**Comment by fiamma06** [comment]
Register at https://imeidb.xyz and use our API for getting data.

**Comment by sovi123** [comment]
Thank you for your replaying.I will try this.

**Comment by sovi123** [comment]
> Register at https://imeidb.xyz and use our API for getting data.

Would you provide the latest database dump? If so, what is the price?

**Comment by fiamma06** [comment]
Yes. But only for personal use.  Price $ 1600

**Comment by sovi123** [comment]
Thanks, a little expensive, I will consider it.

**Comment by fiamma06** [comment]
Welcome :)

**Comment by VTSTech** [comment]
That database (.xyz) is in no way associated with this project. I sell this software, and it's database for $25 USD -- E-mail orders@nigeltodman.com to place an order.

http://www.nigeltodman.com/imei-validator/

**Comment by Daniel3356** [comment]
@sovi123 
those are the IMEI - TAC
iPhone 15 pro: `35343165` 
iPhone 15: `35388719`
iPhone 14 pro: `35826771`
iPhone 14: `35183649`

Samsung Galaxy S24: `35084944`
Samsung Galaxy S24 Ultra: `35586223`

**Comment by fiamma06** [comment]
yep

ср, 28 авг. 2024 г. в 03:13, Daniel ***@***.***>:
